# Generated by Django 2.1.4 on 2019-01-22 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190122_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lobbies',
        ),
    ]
