# Generated by Django 2.1.7 on 2019-04-08 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='invitator',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='invited',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
