# Generated by Django 2.1.7 on 2019-04-29 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
