# Generated by Django 2.1.4 on 2019-01-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('members', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
