# Generated by Django 2.1.4 on 2019-01-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_lobbies'),
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='users',
            field=models.ManyToManyField(to='accounts.Profile'),
        ),
    ]
