# Generated by Django 2.1.4 on 2019-01-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0002_queue_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='users',
            new_name='usrs',
        ),
    ]
