# Generated by Django 2.1.4 on 2019-01-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0003_auto_20190122_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
