# Generated by Django 2.1.4 on 2019-01-23 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0005_auto_20190123_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lobby.Category'),
        ),
    ]
