# Generated by Django 2.1.4 on 2019-01-25 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_lobbies'),
        ('lobby', '0007_auto_20190123_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Profile')),
                ('queue', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='lobby.Queue')),
            ],
        ),
    ]
