# Generated by Django 2.1.7 on 2019-03-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0010_auto_20190316_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
