# Generated by Django 2.1.7 on 2019-04-08 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0012_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invitator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invited',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Profile'),
        ),
    ]
