# Generated by Django 2.1.7 on 2019-04-09 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lobby', '0013_auto_20190408_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='invitator',
        ),
        migrations.AddField(
            model_name='invitation',
            name='invitator',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Profile'),
        ),
    ]
