# Generated by Django 2.1.7 on 2019-04-20 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lobby', '0017_userinvite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinvite',
            name='queue',
        ),
        migrations.AddField(
            model_name='userinvite',
            name='queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lobby.Queue'),
        ),
        migrations.RemoveField(
            model_name='userinvite',
            name='user',
        ),
        migrations.AddField(
            model_name='userinvite',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
