# Generated by Django 2.1.7 on 2019-04-20 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0018_auto_20190420_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvite',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Profile'),
        ),
    ]
