# Generated by Django 2.1.7 on 2019-06-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0021_auto_20190502_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
